name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Package loading
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      - name: Git user configuration
        run: |
          git config --global user.email "cergmin@gmail.com"
          git config --global user.name "Sergey Minakov"
      - name: Checkout to lib branch
        run: git checkout --orphan lib
      - name: Installing library dependencies
        run:  npm ci
      - name: Building library
        run:  npm run build
      - name: Replace .gitignore with .npmignore
        run: |
          rm .gitignore
          mv .npmignore .gitignore
      - name: Stage library build
        run: |
          git reset
          git add .
      - name: Commit library build
        run: git commit -m "Build"
      - name: Push to lib branch
        run: git push origin HEAD:lib -f
