name: Codecov

on:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Package loading
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Installing pnpm
        run: npm install -g pnpm
      - name: Installing dependencies
        run:  pnpm i --frozen-lockfile
      - name: Installing codecov
        run:  pnpm add -D codecov
      - name: Generating coverage report
        run: pnpm coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
