name: Examples deployment

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Package loading
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      - name: Git user configuration
        run: |
          git config --global user.email "cergmin@gmail.com"
          git config --global user.name "Sergey Minakov"
      - name: Checkout to examples branch
        run: git checkout --orphan examples
      - name: Installing library dependencies
        run:  npm ci
      - name: Installing examples dependencies
        run:  cd examples && npm ci
      - name: Building library
        run:  npm run build
      - name: Building examples
        run:  npm run build-examples
      - name: Stage examples build
        run: git --work-tree examples/build add --all
      - name: Commit examples build
        run: git --work-tree examples/build commit -m "Deploy"
      - name: Push to examples branch
        run: git push origin HEAD:examples --force
