name: Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  js:
    runs-on: ubuntu-latest
    steps:
      - name: Package loading
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Installing ESLint dependencies
        run:  npm install --save-dev eslint-plugin-react @typescript-eslint/parser @typescript-eslint/eslint-plugin
      - name: ESLint check
        run: npx eslint --ext js,jsx,ts,tsx src
  css:
    runs-on: ubuntu-latest
    steps:
      - name: Package loading
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Installing Stylelint dependencies
        run:  npm install --save-dev stylelint-order stylelint-config-idiomatic-order
      - name: Stylelint check
        run: npx stylelint src/**/*.css
